# Generated by Django 5.0.6 on 2024-05-26 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0002_alter_device_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='QGIS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geo_location_lat', models.FloatField(null=True)),
                ('geo_location_long', models.FloatField(null=True)),
                ('ndvi', models.FloatField(null=True)),
                ('gndvi', models.FloatField(null=True)),
                ('lai', models.FloatField(null=True)),
                ('msdvi', models.FloatField(null=True)),
                ('recording_time', models.DateTimeField()),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qgis', to='devices.device')),
            ],
        ),
    ]
