# Generated by Django 5.0.6 on 2024-06-09 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='macaddress',
            new_name='address',
        ),
    ]
