# Generated by Django 4.2.13 on 2024-06-12 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0004_rename_macaddress_device_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="address",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
