# Generated by Django 5.0.6 on 2024-05-26 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0002_alter_device_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geo_location_lat', models.FloatField(null=True)),
                ('geo_location_long', models.FloatField(null=True)),
                ('image_path', models.CharField(max_length=256)),
                ('qr_code', models.TextField()),
                ('recording_time', models.DateTimeField(null=True)),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='devices.device')),
            ],
        ),
    ]
