# Generated by Django 5.0.6 on 2024-06-01 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0002_alter_mobile_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(upload_to='images/')),
                ('mobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mobile.mobile')),
            ],
        ),
    ]
