# Generated by Django 5.0.6 on 2024-06-05 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0003_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobile',
            name='image_path',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
