# Generated by Django 4.2.13 on 2024-06-12 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mobile", "0004_remove_mobile_image_path_delete_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="mobile",
            name="pesticide_name",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="mobile",
            name="pesticide_used",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="mobile",
            name="pesticides_type",
            field=models.IntegerField(null=True),
        ),
    ]
