# Generated by Django 5.0.6 on 2024-05-26 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0002_alter_device_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geo_location_lat', models.FloatField(null=True)),
                ('geo_location_long', models.FloatField(null=True)),
                ('wind_direction', models.CharField(max_length=128, null=True)),
                ('wind_speed', models.CharField(max_length=128, null=True)),
                ('rainfall', models.CharField(max_length=128, null=True)),
                ('sunshine', models.CharField(max_length=128, null=True)),
                ('temperature', models.CharField(max_length=128, null=True)),
                ('humidity', models.CharField(max_length=128, null=True)),
                ('recording_time', models.DateTimeField()),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weather_stations', to='devices.device')),
            ],
        ),
    ]
